In [26]:
import numpy as np
import statistics as stats

In [9]:
#Exr 1 (SAMPLE)
my_array = np.array([8,12,16,24,4])
st_deviation=np.std(my_array, ddof=1)
print(st_deviation)

#the sum of deviations of individual data points from their mean=0

7.694153624668538


In [13]:
#Exr 1 (POPULATION)
my_array = np.array([8,12,16,24,4])
st_deviation=np.std(my_array)
print(st_deviation)

#the sum of deviations of individual data points from their mean=0

6.881860213634101


In [32]:
#Exr 4
my_array=np.array([10, 10, 10, 10, 11, 11, 12, 13, 14, 
15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19,
20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24,
26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29,
30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34,
35, 35, 35, 37, 37, 37, 37, 39, 39, 39,
40, 40, 43, 43, 44, 44,
46, 46, 46, 47, 49,
52, 53, 54])
print(np.median(my_array))
print(stats.mode(my_array))
print(np.mean(my_array))



27.0
29
27.88421052631579


In [42]:
my_array = np.array([8,12,16,24,4,34,15,15,55,22])
print(np.median(my_array))
print(stats.mode(my_array))
print(np.mean(my_array))

15.5
15
20.5


In [43]:
my_array = np.array([9,12,16,24,4,34,15,15,55,22])
print(np.median(my_array))
print(stats.mode(my_array))
print(np.mean(my_array))

15.5
15
20.6


In [51]:
#Exr 9
my_array = np.array([25,25,25,40,40,35,50,50,50,50])
st_deviation=np.std(my_array, )
print(st_deviation)
print(np.median(my_array))
print(np.mean(my_array))


10.44030650891055
40.0
39.0


In [52]:
#Exr 1
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Yanaorfin/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Yanaorfin/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Yanaorfin/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Yanaorfin/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Yanaorfin/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Yanaorfin/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/Yanaorfin/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/Yanaorfin/opt/anaconda3/include']
Supported SIMD extensions in this

In [55]:
#Exr 2 Create a null vector of size 10
def zero_vector(n_values):
    new_array=np.zeros(n_values)
    return new_array

print(zero_vector(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
#Exr 3-4 How to find the memory size of any array
my_array = np.array([25,25,25,40,40,35,50,50,50,50])
print("The size is",my_array.size)
print("The size of memory of one item -",my_array.itemsize,"bytes")
print("The size of memory is -",my_array.itemsize*my_array.size,"bytes")


The size is 10
The size of memory of one item - 8 bytes
The size of memory is - 80 bytes


In [ ]:
#Exr 5 How to get the documentation of the numpy add function from the command line? (★☆☆)

In [67]:
#Exr 6 Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

def zero_vector(n_values,item_position,x_item):
   
    new_array=np.where(np.arange(n_values)==item_position-1,x_item,0)
    return new_array

print(zero_vector(10,5,1))

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
my_array = np.array()
np.arange(my_array,3)

In [71]:
#7 Create a vector with values ranging from 10 to 49 (★☆☆)
new_array=np.arange(10,49)
print(new_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [96]:
#8. Reverse a vector (first element becomes last) (★☆☆)

#new_array=np.arange(49,10,-1)
#print(new_array)

current_array=np.array([10, 11, 12, 13, 14, 15])


print(current_array[::-1])
reve=np.flip(current_array)
print(reve)

[15 14 13 12 11 10]
[15 14 13 12 11 10]


In [ ]:
#9. Create a 3x3 matrix with values ranging from 0 to 8

#def new_matrix(count_level,first_item,last_item):
    x=np.matrix()